version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: task3
    ports:
      - 9898:80
    volumes:
      - .:/var/www
    links:
      - redis
    environment:
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
  redis:
    image: redis:4.0-alpine
    ports:
      - 16379:6379